sudo: false
dist: trusty
language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/

script:
  - echo "Nothing about build the code."

before_deploy:
  - export RELEASE_BODY=`echo 'Update '$TRAVIS_TAG'<br><br>Check \`hashes.json\` and \`change.json\`'`

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - "hashes.json"
    - "changes.json"
  skip_cleanup: true
  on:
    tags: true
    branch: master

  name: Update ${TRAVIS_TAG}
  body: ${RELEASE_BODY}

